### PR TITLE
Fix bug when edit job clears the respective interviews

### LINKED ISSUE #119: [BUG] Interviews cleared whenever an edit is made to its Job
**Current Situation**
- editing any fields of the job will clear the list of interviews
- even the data of interviews will be clear in the backend

Optimal Outcome
- editing any fields of the job does not clear the interviews
- only edits the job fields and change UI display in the JobCard and JobDetailsPanel

### PR DESCRIPTION
**Pull request by evanyan13**
- Update implementation of `editJobDescriptor` to include interviews when edited
- Update `isValidInterviewDateTime` method to suit the current implement for `Deadline`
- Closes #119

### CODE REVIEW

File: src/main/java/seedu/application/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -111,8 +112,10 @@ private static Job createEditedJob(Job jobToEdit, EditJobDescriptor editJobDescr
         Status updatedStatus = editJobDescriptor.getStatus().orElse(jobToEdit.getStatus());
         JobType updatedJobType = editJobDescriptor.getJobType().orElse(jobToEdit.getJobType());
         Industry updatedIndustry = editJobDescriptor.getIndustry().orElse(jobToEdit.getIndustry());
+        List<Interview> updatedInterviews = editJobDescriptor.getInterviews().orElse(jobToEdit.getInterviews());
 
-        return new Job(updatedRole, updatedCompany, updatedDeadline, updatedStatus, updatedJobType, updatedIndustry);
+        return new Job(updatedRole, updatedCompany, updatedDeadline, updatedStatus, updatedJobType,
```
Comment (migfoo02) [inline src/main/java/seedu/application/logic/commands/EditCommand.java:117]: Good observation that this was causing the bug.

**Review by migfoo02 — APPROVED** [review]
LGTM
