### PR TITLE
Edit GUI Bug for clear command clearing job details panel

### LINKED ISSUE #81: [GUI BUG] JobDetailsPanel not updating after "clear" command
### Current Situation
- After executing clear command, the job list gets correctly clear. However, the JobDetailsPanel is still showing the details of the deleted task.

### Ideal Situation
- JobDetailsPanel updates after "clear command" - not show any detail for any job as there is no job in the list anymore
- Consider what other errors may other commands may cause as well

Screenshot 2023-10-25 at 8 10 56 PM

### PR DESCRIPTION
**Pull request by evanyan13**
- JobDetailsPanel updates after "clear command" - not show any detail for any job as there is no job in the list anymore
- Closes #81

### CODE REVIEW

**Review by czhiruo — APPROVED** [review]
LGTM

File: src/main/java/seedu/application/logic/commands/CommandResult.java [hunk 1]
```diff
@@ -13,20 +13,29 @@ public class CommandResult {
...
+     * The window should be cleared.
+     */
+    private final boolean clear;
     private final int interview;
 
     /**
      * Constructs a {@code CommandResult} with the specified fields.
      */
-    public CommandResult(String feedbackToUser, boolean showHelp, boolean exit, int interview) {
+    public CommandResult(String feedbackToUser, boolean showHelp, boolean exit, boolean clear, int interview) {
```
Comment (migfoo02) [inline src/main/java/seedu/application/logic/commands/CommandResult.java:34]: Good use of CommandResult to update main window

**Review by migfoo02 — APPROVED** [review]
LGTM
